(()=>{'use strict';
const API='https://asia-east1-youzi-c1b74.cloudfunctions.net/groupBuyApi';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>'NT$ '+Number(n||0).toLocaleString('zh-TW');
const adminPage=document.body.dataset.admin==='true';let user=null,config=null,tab='orders',cart={},noPurchase=false,selectedClass='',selectedMember='',requestId=crypto.randomUUID(),sending=false,dirty=false;
const notify=(s,error=false)=>{if(error&&window.ClubConsent?.reportError(s))return;const m=$('#message');m.textContent=s;m.style.color=error?'#93462f':'';m.style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>m.style.display='none',6000);};
async function api(action,payload={}){const headers={'Content-Type':'application/json'};if(adminPage&&user)headers.Authorization='Bearer '+await user.getIdToken();const r=await fetch(API,{method:'POST',headers,body:JSON.stringify({action,payload})});const d=await r.json();if(!r.ok)throw Error(d.error||'連線失敗，請稍後重試');return d;}
const stock=p=>p.unlimited?'<span class="stock">不限量</span>':p.total===null?'<span class="stock empty">數量待設定</span>':`<span class="stock ${p.total-p.reserved<=2?'low':''} ${p.total===p.reserved?'empty':''}">${p.total===p.reserved?'已額滿':'剩餘 '+(p.total-p.reserved)+(p.kind==='book'?' 本':' 支')}</span>`;
const photo=p=>p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" referrerpolicy="no-referrer">`:`<div class="placeholder"><b>${esc(p.name.replace('木吉他-',''))}</b>商品照片整理中</div>`;
function protectImageFailures(){document.querySelectorAll('.photo img').forEach(im=>im.addEventListener('error',()=>{const el=document.createElement('div');el.className='placeholder';el.textContent='商品照片暫時無法載入';im.replaceWith(el);},{once:true}));}
function loadError(message){$('#app').innerHTML='<div class="panel"><p>'+esc(message)+'</p><button id="retry">重新載入</button></div>';$('#retry').onclick=()=>loadMember().catch(e=>loadError(e.message));}
async function loadMember(){const d=await api('catalog');config=d.data;config.isAdmin=d.isAdmin;renderMember();}
function renderMember(){
 $('#title').textContent='團購吉他';
 const classes=[...new Set(config.roster.map(x=>x.className))];
 $('#app').innerHTML=`${!config.open?'<div class="notice">目前未開放填寫</div>':''}<div class="grid">${config.products.map((p,i)=>`<article class="card ${cart[p.id]===1?'selected':''}"><div class="photo">${photo(p)}</div><div class="card-body"><h3>${esc(p.name.replace('木吉他-',''))}</h3><p class="desc" style="white-space:pre-line">${esc(p.description)}</p><div class="line"><div class="price"><small>NT$</small>${p.price.toLocaleString('zh-TW')}</div>${stock(p)}</div><div class="card-bottom"><label class="choose-guitar"><input type="checkbox" data-product="${p.id}" aria-label="選擇 ${esc(p.name)}" ${cart[p.id]===1?'checked':''} ${!config.open||!p.enabled||(!p.unlimited&&(p.total===null||p.total<=p.reserved))?'disabled':''}> ${p.kind==='book'?(cart[p.id]===1?'已選這本':'選這本'):(cart[p.id]===1?'已選這把':'選這把')}</label></div></div></article>`).join('')}</div><section class="panel checkout"><div class="fields">${!config.roster.length?`<label>班級<input id="freeClass" value="${esc(selectedClass)}" placeholder="請填班級" maxlength="60"></label><label>姓名<input id="freeName" value="${esc(selectedMember)}" placeholder="請填姓名" maxlength="60"></label>`:`<label>班級<select id="class"><option value="">${classes.length?'請選擇班級':'請填班級'}</option>${classes.map(c=>`<option ${c===selectedClass?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>姓名<select id="member"><option value="">請先選擇班級</option></select></label>`}</div><div id="selection" class="summary"></div><div id="parentConsent"></div><div class="line" style="margin-top:25px;border-top:1px solid var(--line);padding-top:22px"><div><span class="muted">合計</span><div class="total" id="total"></div></div><button id="submit" ${!config.open?'disabled':''}>送出</button></div></section>`;
 function names(){$('#member').innerHTML='<option value="">請選擇姓名</option>'+config.roster.filter(m=>m.className===selectedClass).map(m=>`<option value="${m.id}" ${m.id===selectedMember?'selected':''}>${esc(m.name)}</option>`).join('');}
 if(config.roster.length){names();$('#class').onchange=e=>{selectedClass=e.target.value;selectedMember='';names();};$('#member').onchange=e=>selectedMember=e.target.value;}else{$('#freeClass').oninput=e=>{selectedClass=e.target.value;ClubConsent.resetSignature();ClubConsent.refreshSummary();};$('#freeName').oninput=e=>{selectedMember=e.target.value;ClubConsent.resetSignature();ClubConsent.refreshSummary();};}
 document.querySelectorAll('[data-product]').forEach(el=>el.onchange=()=>{const p=config.products.find(p=>p.id===el.dataset.product);if(el.checked){if(p.kind!=='book')for(const q of config.products.filter(q=>q.kind!=='book'))delete cart[q.id];cart[p.id]=1;}else delete cart[p.id];noPurchase=false;ClubConsent.resetSignature();requestId=crypto.randomUUID();renderMember();});
 $('#submit').onclick=submit;protectImageFailures();totals();ClubConsent.mount($('#parentConsent'),{noPurchase,onChange:()=>{requestId=crypto.randomUUID();},getSummary:()=>({className:selectedClass,name:selectedMember,items:config.products.filter(p=>cart[p.id]>0).map(p=>({id:p.id,name:p.name,quantity:cart[p.id],price:p.price,description:p.description})),total:config.products.reduce((n,p)=>n+p.price*(cart[p.id]||0),0)})});
}
function totals(){const lines=config.products.filter(p=>cart[p.id]>0);$('#selection').textContent=noPurchase?'已選擇：本次不購買':lines.length?lines.map(p=>`${p.name.replace('木吉他-','')} × ${cart[p.id]}`).join(' ／ '):'尚未選擇商品';$('#total').textContent=money(lines.reduce((n,p)=>n+p.price*cart[p.id],0));}
async function submit(){if(sending)return;if(!selectedMember.trim()||!selectedClass.trim())return notify('請填寫班級與姓名',true);const items=Object.entries(cart).filter(([,q])=>q>0).map(([id,quantity])=>({id,quantity}));if(!items.length)return notify('請先選擇吉他或書本',true);let consent;try{consent=ClubConsent.value(noPurchase);}catch(e){return notify(e.message,true);}sending=true;ClubConsent.setBusy(true);$('#submit').disabled=true;try{const r=await api('submit',{memberId:config.roster.length?selectedMember:undefined,className:selectedClass,name:config.roster.length?undefined:selectedMember,items,noPurchase,requestId,consent,expectedTotal:config.products.reduce((n,p)=>n+p.price*(cart[p.id]||0),0)});ClubConsent.release();$('#app').innerHTML=`<div class="panel success"><div class="tick">✓</div><h2>已送出</h2><div class="total">${money(r.data.total)}</div><p class="muted">登記編號：${esc(r.data.id)}</p></div>`;window.scrollTo({top:0,behavior:'smooth'});}catch(e){notify(e.message,true);$('#submit').disabled=false;}finally{sending=false;ClubConsent.setBusy(false);}}
async function loadAdmin(){const d=await api('adminLoad');config=d.data;dirty=false;renderAdmin();}
function adminLogin(message){$('#app').innerHTML=`<section class="panel gate"><h2>管理者登入</h2><p>${esc(message||'請先使用現有營運系統管理者帳號登入。')}</p><a class="button" href="login.html?next=group-buy-admin.html">前往登入</a></section>`;}
function renderAdmin(){const active=config.orders.filter(o=>o.status==='active');const qty=active.reduce((n,o)=>n+o.items.filter(p=>config.products.find(x=>x.id===p.id)?.kind!=='book').reduce((s,p)=>s+p.quantity,0),0),amount=active.reduce((n,o)=>n+o.total,0);$('#app').innerHTML=`<div class="notice">${config.open?'● 填單開放中':'○ 尚未開放填單'} · 社員網址：<a href="group-buy.html" target="_blank" rel="noopener">開啟團購頁 ↗</a></div><div class="stats"><div class="stat"><span>有效登記 / 含不購買</span><strong>${active.length}</strong></div><div class="stat"><span>已訂購吉他</span><strong>${qty} <small style="font-size:14px">支</small></strong></div><div class="stat"><span>訂購總額</span><strong style="font-size:24px">${money(amount)}</strong></div><div class="stat"><span>剩餘數量</span><strong>${config.products.reduce((sum,p)=>sum+(p.total===null?0:p.total-p.reserved),0)}</strong></div></div><nav class="tabs">${[['orders','登記與數量'],['products','商品與數量'],['settings','填單設定']].map(([id,name])=>`<button data-tab="${id}" class="${tab===id?'active':''}">${name}</button>`).join('')}</nav><div id="adminBody"></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(dirty&&!confirm('尚有未儲存的修改，確定離開此頁？'))return;dirty=false;tab=b.dataset.tab;renderAdmin();});if(tab==='orders')renderOrders();if(tab==='products')renderProducts();if(tab==='settings')renderSettings();}
function renderOrders(){const classes=[...new Set(config.orders.map(o=>o.className))];$('#adminBody').innerHTML=`<div class="panel"><div class="line"><h2>填選明細</h2><div class="toolbar"><select id="filterClass" aria-label="依班級篩選" style="width:150px"><option value="">全部班級</option>${classes.map(c=>`<option>${esc(c)}</option>`).join('')}</select><button id="export" class="secondary">匯出 CSV</button></div></div><div class="table-wrap"><table><thead><tr><th>班級 / 姓名</th><th>商品與數量</th><th>金額</th><th>狀態</th><th>操作</th></tr></thead><tbody id="orderRows"></tbody></table></div></div><div class="panel"><h2>商品統計</h2><div class="table-wrap"><table><thead><tr><th>商品</th><th>總配額</th><th>已訂購</th><th>剩餘</th></tr></thead><tbody>${config.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.unlimited?'不限量':p.total??'待設定'}</td><td>${p.reserved}</td><td>${p.unlimited?'不限量':p.total===null?'待設定':p.total-p.reserved}</td></tr>`).join('')}</tbody></table></div></div>`;
 function rows(){const c=$('#filterClass').value,os=config.orders.filter(o=>!c||o.className===c);$('#orderRows').innerHTML=os.length?os.map(o=>`<tr><td>${esc(o.className)}<br><strong>${esc(o.name)}</strong></td><td>${o.noPurchase?'本次不購買':o.items.map(p=>`${esc(p.name)} × ${p.quantity}`).join('<br>')}<br><small class="muted">${esc(new Date(o.createdAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}))}</small></td><td>${money(o.total)}</td><td>${o.status==='cancelled'?'已取消':o.noPurchase?'不購買':'已登記'}<br>${o.consentSummary?`<button class="secondary" data-consent="${o.id}">查看家長同意</button>`:o.noPurchase?'':`<small class="muted">未留存家長簽名</small>`}</td><td>${o.status==='active'?`<button class="secondary" data-edit="${o.id}">修改</button> <button class="danger" data-cancel="${o.id}">取消</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="5" style="padding:40px;text-align:center;color:var(--muted)">目前還沒有登記，社員填單後會顯示在這裡。</td></tr>';document.querySelectorAll('[data-consent]').forEach(b=>b.onclick=async()=>{try{const r=await api('getConsent',{id:b.dataset.consent});ClubConsent.show($('#order-dialog'),r.data);}catch(e){notify(e.message,true);}});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editOrder(b.dataset.edit));document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{if(!confirm('取消這筆登記並歸還團購名額？'))return;b.disabled=true;try{await api('cancelOrder',{id:b.dataset.cancel});await loadAdmin();notify('登記已取消，名額已歸還');}catch(e){notify(e.message,true);b.disabled=false;}});}
 $('#filterClass').onchange=rows;rows();$('#export').onclick=()=>{const rows=[['班級','姓名','商品','數量','單價','小計','登記狀態','登記時間']];for(const o of config.orders.filter(o=>!$('#filterClass').value||o.className===$('#filterClass').value)){for(const p of o.items.length?o.items:[{name:'本次不購買',quantity:0,price:0}])rows.push([o.className,o.name,p.name,p.quantity,p.price,p.price*p.quantity,o.status==='active'?'有效':'已取消',o.createdAt]);}const cell=x=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const blob=new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='社團團購登記.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};}
function editOrder(id){const o=config.orders.find(o=>o.id===id),d=$('#order-dialog');d.innerHTML=`<h2>修改 ${esc(o.className)} ${esc(o.name)} 的登記</h2><form id="editOrderForm">${config.products.map(p=>`<label class="line">${esc(p.name)}<input type="number" min="0" max="8" style="width:80px" data-order-item="${p.id}" value="${o.items.find(x=>x.id===p.id)?.quantity||0}"></label>`).join('')}<label><input id="editNone" type="checkbox" ${o.noPurchase?'checked':''}> 本次不購買（請將所有商品數量設為 0）</label><p class="muted" style="font-size:12px">修改商品後，金額依目前團購價重新計算。</p><div class="toolbar"><button>儲存修改</button><button type="button" id="closeDialog" class="secondary">返回</button></div></form>`;d.showModal();$('#closeDialog').onclick=()=>d.close();$('#editOrderForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const items=[...document.querySelectorAll('[data-order-item]')].filter(el=>Number(el.value)>0).map(el=>({id:el.dataset.orderItem,quantity:Number(el.value)}));await api('updateOrder',{id,updatedAt:o.updatedAt,items,noPurchase:$('#editNone').checked});d.close();await loadAdmin();notify('登記已更新');}catch(e){notify(e.message,true);b.disabled=false;}};}
function renderProducts(){$('#adminBody').innerHTML=`<section class="panel"><div class="line"><h2>商品與團購配額</h2><button id="saveProducts">儲存商品設定</button></div><p class="muted">「總配額」包含已訂購數量，剩餘數量會自動扣除。留白代表數量待設定，暫停接受該商品訂購。</p><div id="productEditors">${config.products.map(p=>`<div class="edit-card" data-editor="${p.id}"><div>${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:'<span class="muted">待補圖</span>'}</div><label class="product-name">商品名稱<input name="name" value="${esc(p.name)}" maxlength="120"></label><label>團購價<input name="price" type="number" min="0" value="${p.price}"></label><label class="total-field">總配額<input name="total" type="number" min="${p.reserved}" value="${p.total??''}" placeholder="待設定"><small class="muted">已訂 ${p.reserved} ${p.kind==='book'?'本':'支'}</small><label><input name="unlimited" type="checkbox" ${p.unlimited?'checked':''}> 不限量</label></label><div class="wide"><label>簡短介紹<input name="description" value="${esc(p.description)}" maxlength="500"></label><label>商品圖片網址<input name="image" value="${esc(p.image)}" placeholder="https://…"></label><label><input name="enabled" type="checkbox" ${p.enabled?'checked':''}> 開放此商品訂購</label></div></div>`).join('')}</div><button id="addProduct" class="secondary" style="margin-top:20px">＋ 新增商品</button></section>`;$('#productEditors').oninput=()=>dirty=true;const collect=()=>[...document.querySelectorAll('[data-editor]')].map(el=>({id:el.dataset.editor,kind:config.products.find(p=>p.id===el.dataset.editor)?.kind||'guitar',unlimited:el.querySelector('[name=unlimited]').checked,name:el.querySelector('[name=name]').value,price:Number(el.querySelector('[name=price]').value),total:el.querySelector('[name=total]').value===''?null:Number(el.querySelector('[name=total]').value),image:el.querySelector('[name=image]').value,description:el.querySelector('[name=description]').value,enabled:el.querySelector('[name=enabled]').checked}));$('#saveProducts').onclick=async e=>{e.target.disabled=true;try{await api('saveSettings',{...config,products:collect()});await loadAdmin();notify('商品設定已儲存');}catch(err){notify(err.message,true);e.target.disabled=false;}};$('#addProduct').onclick=()=>{config.products=collect().map(p=>({...p,reserved:config.products.find(x=>x.id===p.id)?.reserved||0}));config.products.push({id:'item-'+crypto.randomUUID(),name:'新商品',price:0,total:null,reserved:0,image:'',description:'',enabled:false});dirty=true;renderProducts();};}
function renderSettings(){$('#adminBody').innerHTML='<section class="panel"><h2>填單設定</h2><label><input id="settingOpen" type="checkbox" '+(config.open?'checked':'')+'> 開放填單</label><button id="saveSettings">儲存</button></section>';$('#saveSettings').onclick=async e=>{e.target.disabled=true;try{await api('saveSettings',{...config,title:'團購吉他',intro:'',roster:[],open:$('#settingOpen').checked});await loadAdmin();notify('已儲存');}catch(err){notify(err.message,true);e.target.disabled=false;}};}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function start(){if(adminPage)try{firebase.initializeApp(APP_CONFIG.FIREBASE_CONFIG);user=await new Promise(resolve=>{const unsub=firebase.auth().onAuthStateChanged(u=>{unsub();resolve(u);});});}catch(e){user=null;}if(adminPage){$('#refresh').onclick=()=>{if(dirty&&!confirm('尚有未儲存修改，確定重新整理？'))return;loadAdmin().catch(e=>notify(e.message,true));};if(!user)return adminLogin();try{await loadAdmin();}catch(e){adminLogin(e.message);}}else{try{await loadMember();}catch(e){loadError('目前連線不穩，請按重新載入。');}setInterval(async()=>{if(!config||!$('#total')||sending||document.hidden||ClubConsent.isDrawing()||document.activeElement?.matches('input,select,textarea'))return;try{const d=await api('catalog');if(ClubConsent.isDrawing()||sending||d.data.revision===config.revision)return;if(JSON.stringify(config.products.map(p=>[p.id,p.name,p.price,p.description]))!==JSON.stringify(d.data.products.map(p=>[p.id,p.name,p.price,p.description])))ClubConsent.resetSignature();config=d.data;config.isAdmin=d.isAdmin;renderMember();}catch(e){}},45000);}}
start();
})();
