'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const backend=fs.readFileSync('functions/coursePortal.js','utf8');
const extract=name=>{const start=backend.search(new RegExp('(?:async )?function '+name+'\\('));assert(start>=0);return backend.slice(start,backend.indexOf('\n}',start)+2);};
function client(invoke=async()=>({ok:true})){const calls=[];let auth=0;const window={console:{info(){}},APP_CONFIG:{FIREBASE_CONFIG:{projectId:'test'}},YouziOperationsManagerAuth:{ensureManagerAuth:async()=>{auth++;return {ok:true};}},firebase:{apps:[{}],initializeApp(){},app:()=>({functions:region=>({httpsCallable:name=>async data=>{calls.push({region,name,data});return {data:await invoke(data,name)};}})})}};vm.runInNewContext(fs.readFileSync('course-scheduler-data.js','utf8'),{window});return {api:window.YouziCoursePreviewData,calls,auth:()=>auth};}
const event=(id,date,studentId)=>({id,date,studentIds:[studentId],roomId:'room',start:'10:30',duration:60});
test('scoped refresh removes deleted period, attendance and payroll without touching other students or dates',()=>{
 const {api}=client(),keep={id:'p2',studentId:'s2',transactions:[{amount:2800}]};
 const state={students:[{id:'s1',name:'學生'}],feePlans:[],tuitionPeriods:[{id:'p1',studentId:'s1'},keep],attendance:[{id:'a1',studentId:'s1'},{id:'a2',studentId:'s2'}],teacherPayroll:[{id:'w1',teacherId:'t',date:'2026-09-18'},{id:'w2',teacherId:'t',date:'2026-09-19'}],teacherAdjustments:[{id:'j1',teacherId:'t',date:'2026-09-18'},{id:'j2',teacherId:'other',date:'2026-09-18'}],events:[event('old','2026-09-18','s1'),event('other','2026-09-18','s2'),event('later','2026-09-19','s1')],dataMeta:{version:1}};
 api.applyWorkspaceSlice(state,{studentIds:['s1'],payrollScopes:[{teacherId:'t',date:'2026-09-18'}],tuitionPeriods:[],attendance:[],teacherPayroll:[],adjustmentScopes:[{teacherId:'t',month:'2026-09'}],teacherAdjustments:[],calendars:[{scope:{startDate:'2026-09-18',endDate:'2026-09-18',studentIds:['s1']},events:[event('new','2026-09-18','s1')]}],version:2});
 assert.equal(state.tuitionPeriods[0],keep);assert.equal(state.tuitionPeriods.length,1);assert.equal(state.attendance[0].id,'a2');assert.equal(state.teacherPayroll[0].id,'w2');assert.equal(state.teacherAdjustments[0].id,'j2');assert.deepEqual(Array.from(state.events,e=>e.id).sort(),['later','new','other']);assert.equal(state.events.find(e=>e.id==='new').studentNames[0],'學生');assert.equal(state.dataMeta.version,2);
});
test('empty calendar result clears the requested day, preserves other days and rental fields',()=>{const {api}=client(),state={students:[],feePlans:[],tuitionPeriods:[],attendance:[],teacherPayroll:[],events:[event('old','2026-09-18','s'),event('later','2026-09-19','s')]};api.applyWorkspaceSlice(state,{calendars:[{scope:{startDate:'2026-09-18',endDate:'2026-09-18'},events:[]}]});assert.deepEqual(Array.from(state.events,e=>e.id),['later']);api.applyWorkspaceSlice(state,{calendars:[{scope:{startDate:'2026-09-18',endDate:'2026-09-18'},events:[{...event('rent','2026-09-18',''),type:'rental',portalBookingId:'booking',rentalPaymentStatus:'paid',rentalFee:300}]}]});assert.equal(state.events.find(e=>e.id==='rent').portalBookingId,'booking');assert.equal(state.events.find(e=>e.id==='rent').rentalFee,300);});
test('only read snapshots retry a version conflict; uncertain financial writes are never retried',async()=>{let count=0;const f=client(async()=>{if(++count===1)throw Object.assign(Error('changed'),{code:'functions/aborted'});return {ok:true};});await f.api.refreshWorkspaceSlice({studentIds:['s']});assert.equal(count,2);assert.equal(f.auth(),2);assert(f.calls.every(c=>c.name==='coursePortalAdminWorkspaceSliceTaiwan'&&c.region==='asia-east1'));const failure=client(async()=>{throw Object.assign(Error('uncertain'),{code:'functions/unavailable'});});await assert.rejects(failure.api.recordTuitionTransaction({id:'pay'}),/uncertain/);assert.equal(failure.calls.length,1);});
test('Taiwan desktop endpoints all authorize before invoking their original business handler',async()=>{
 const start=backend.indexOf('  const desktopTaiwanHandlers='),end=backend.indexOf('  exportsObject.coursePortalAdminTuitionPaymentScreenshot',start),code=backend.slice(start,end),exportsObject={},calls=[];let allowed=false;
 const ctx={exportsObject,ADMIN_PIN:'pin-reference',callable:(handler,options)=>({handler,options}),withPortalReads:f=>f,withOperationTiming:(_n,_r,f)=>f,timeOperationStage:(_n,f)=>f(),assertAdminPin:()=>{if(!allowed)throw Error('denied');}};
 for(const match of code.matchAll(/coursePortal\w+:(admin\w+)/g))ctx[match[1]]=data=>{calls.push({handler:match[1],data});return {ok:true};};
 vm.runInNewContext(code,ctx);assert.equal(Object.keys(exportsObject).length,18);
 for(const entry of Object.values(exportsObject)){await assert.rejects(entry.handler({id:'x'},{}),/denied/);assert.equal(entry.options.region,'asia-east1');}
 assert.equal(calls.length,0);allowed=true;for(const entry of Object.values(exportsObject))assert.equal((await entry.handler({id:'x'},{})).ok,true);assert.equal(calls.length,18);
});
test('receipt lookup only queries the requested period and retains deletion and group projection',async()=>{
 const reads=[],doc=(id,data)=>({id,exists:!!data,data:()=>data}),ctx={jsonValue:x=>x,clean:x=>String(x||''),sourceId:r=>r.id||r.__id,MIRROR:{tuitionPeriods:'mirror'},TUITION_PERIODS:'periods',TUITION_TRANSACTIONS:'transactions',TUITION_RECEIPTS:'receipts',readCourseGroups:async()=>[],projectCourseGroups:(_kind,rows)=>rows,HttpsError:Error};
 let deleted=false;
 ctx.db={collection:name=>({where:(field,op,value)=>({get:async()=>{reads.push({name,field,op,value});return {docs:name==='mirror'?[doc('m',{source:{id:'p',studentId:'s',transactions:[]}})]:[]};}}),doc:id=>({get:async()=>{reads.push({name,id});return doc(id,deleted?{id,active:false,status:'deleted'}:undefined);}})})};
 for(const name of ['firstFiniteNumber','transactionAmount','tuitionBasePaidAmount','mergePortalTuitionRows','tuitionPeriodById'])vm.runInNewContext(extract(name),ctx);
 assert.equal((await ctx.tuitionPeriodById('p')).id,'p');assert.equal(reads.length,4);assert(reads.every(r=>r.value==='p'||r.id==='p'));deleted=true;assert.equal(await ctx.tuitionPeriodById('p'),undefined);
});
test('workspace response rejects an inconsistent snapshot and preserves all conflict inputs for permanent moves',async()=>{
 let version=1;const ctx={clean:x=>String(x||''),dateKey:x=>/^\d{4}-\d{2}-\d{2}$/.test(x||'')?x:'',addDays:(s,n)=>new Date(Date.parse(s)+n*86400000).toISOString().slice(0,10),HttpsError:class extends Error{constructor(code,msg){super(msg);this.code=code;}},readScheduleVersion:async()=>version++,timeOperationStage:(_n,f)=>f(),adminAttendanceDetail:async data=>{assert.equal(data.allowEmptyStudents,true);return {ok:true};},scheduleBundle:async(_s,_e,_t,opts)=>{assert.equal(opts.historyStudentId,undefined);return {managerEvents:[event('e','2026-09-18','s')]};},eventStudentIds:r=>r.studentIds,sourceId:r=>r.id};vm.runInNewContext(extract('adminWorkspaceSlice'),ctx);await assert.rejects(ctx.adminWorkspaceSlice({calendarScopes:[{startDate:'2026-09-18',endDate:'2026-09-18',studentIds:['s']}]}),e=>e.code==='aborted');
});
test('operation timings preserve results and errors and omit personal data',async()=>{const {createOperationTiming}=require('../functions/courseOperationTiming'),rows=[],timing=createOperationTiming({log:r=>rows.push(r)}),error=Object.assign(Error('private-message'),{code:'permission-denied'});await assert.rejects(timing.withOperationTiming('save','asia-east1',()=>timing.timeOperationStage('authorize',()=>{throw error;}))({studentId:'private-id'},{}),e=>e===error);assert.equal(rows[0].outcome,'error');assert.equal(rows[0].stages[0].stage,'authorize');assert(!JSON.stringify(rows).includes('private'));const broken=createOperationTiming({log:()=>{throw Error('logging');}});assert.equal(await broken.withOperationTiming('save','asia-east1',()=>42)({},{}),42);});

for(const file of ['course-scheduler.js','operations-course-inline-runtime.js'])test(file+': moving a lesson refreshes both days and permanent move refreshes the affected student range',async()=>{
 const source=fs.readFileSync(file,'utf8'),start=source.indexOf('  async function persistScheduleChange('),end=source.indexOf('\n  function nextPeriodNumber',start),refreshes=[],writes=[];
 const ctx={$:()=>({classList:{add(){}}}),state:{currentDate:'2026-09-18',dataMeta:{rangeStart:'2026-01-21',rangeEnd:'2027-11-12'}},window:{YouziCoursePreviewData:{saveSchedule:async data=>{writes.push(data);return {ok:true};},loadPublished:()=>{throw Error('full reload is forbidden after this write');}}},storedMigrationPin:()=>'',uid:()=> 'operation',refreshSavedWorkspace:async data=>refreshes.push(data),renderCalendar(){}};
 vm.runInNewContext(source.slice(start,end),ctx);const old=event('old','2026-09-18','s'),next=event('next','2026-09-19','s');await ctx.persistScheduleChange(next,{source:old});assert.equal(writes.length,1);assert.deepEqual(Array.from(refreshes[0].calendarScopes,s=>s.startDate),['2026-09-18','2026-09-19']);await ctx.persistScheduleChange(next,{source:old,mode:'permanent_move'});const scope=refreshes[1].calendarScopes.at(-1);assert.equal(scope.startDate,'2026-01-21');assert.equal(scope.endDate,'2027-11-12');assert.deepEqual(Array.from(scope.studentIds),['s']);
});
test('failed refresh is explicitly marked saved and never replays the mutation',async()=>{const source=fs.readFileSync('course-scheduler.js','utf8'),start=source.indexOf('  async function refreshSavedWorkspace('),end=source.indexOf('  async function persistScheduleChange(',start);let calls=0;const ctx={window:{YouziCoursePreviewData:{refreshWorkspaceSlice:async()=>{calls++;throw Error('offline');}}},storedMigrationPin:()=>'',clean:x=>String(x||'')};vm.runInNewContext(source.slice(start,end),ctx);await assert.rejects(ctx.refreshSavedWorkspace({studentIds:['s']}),e=>e.saved===true&&e.message.includes('雲端已儲存成功'));assert.equal(calls,1);});
test('an issued cached receipt returns without loading students or rerendering',async()=>{
 let studentReads=0;const ctx={clean:x=>String(x||''),dateKey:x=>x,transactionAmount:r=>r.amount,hash:()=> '123456789012345678901234',timeOperationStage:(_n,f)=>f(),tuitionPeriodById:async()=>({id:'p',studentId:'s',transactions:[{id:'pay',type:'payment',date:'2026-09-18',amount:2800,method:'cash'}]}),TUITION_RECEIPTS:'receipts',db:{collection:()=>({doc:()=>({get:async()=>({exists:true,data:()=>({status:'issued',imageUrl:'https://example.com/receipt.png'})})})})},mirrorProfilesByIds:async()=>{studentReads++;throw Error('unnecessary student read');},HttpsError:Error};vm.runInNewContext(extract('adminEnsureTuitionReceipt'),ctx);const result=await ctx.adminEnsureTuitionReceipt({periodId:'p',transactionId:'pay'});assert.equal(result.created,false);assert.equal(studentReads,0);assert.equal(result.receiptImageUrl,'https://example.com/receipt.png');
});
test('refresh retains visible occurrence identity so open course details and attendance links remain valid',()=>{const {api}=client(),state={students:[],feePlans:[],tuitionPeriods:[],attendance:[],teacherPayroll:[],events:[{...event('display-id','2026-09-18','s'),sourceId:'canonical-id'}]};api.applyWorkspaceSlice(state,{calendars:[{scope:{startDate:'2026-09-18',endDate:'2026-09-18'},events:[{...event('canonical-id@2026-09-18','2026-09-18','s'),sourceId:'canonical-id',teacherPayAdjustment:100}]}]});assert.equal(state.events.length,1);assert.equal(state.events[0].id,'display-id');assert.equal(state.events[0].teacherPayAdjustment,100);});
