const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const model=require('../functions/inventoryAverageCost');
const raw={averageCost:8000,latestPurchaseCost:8200,currentStock:2,costLayers:[{layerId:'old',qtyRemaining:2,unitCost:14500}]};
test('manual average is authoritative despite contradictory old FIFO batches',()=>{const r=model.consume(raw,1);assert.equal(r.costTotal,8000);assert.equal(r.averageCost,8000);assert.equal(r.inventoryValue,8000);assert.equal(raw.costLayers[0].unitCost,14500);});
test('selling out and negative stock preserve manually entered cost',()=>{for(const qty of [2,3]){const r=model.consume(raw,qty,true);assert.equal(r.costTotal,qty*8000);assert.equal(r.averageCost,8000);assert.equal(r.inventoryValue,0);}assert.throws(()=>model.consume(raw,3,false),/庫存不足/);});
test('missing or invalid average cannot silently use selling price, purchase cost or FIFO',()=>{for(const value of [null,undefined,'',-1,NaN])assert.throws(()=>model.consume({...raw,averageCost:value},1,true),/平均成本/);assert.equal(model.consume({...raw,averageCost:0},1).costTotal,0);});
const src=fs.readFileSync('operations-phase1.js','utf8');
function extract(name){const a=src.indexOf('  function '+name+'('),line=src.indexOf('\n',a);if(src.slice(a,line).trim().endsWith('}'))return src.slice(a,line);return src.slice(a,src.indexOf('\n  }',a)+4);}
const ctx={global:{YouziInventoryAverageCost:model},uid:()=> 'receipt',numberOrNull:x=>x==null?null:Number(x)};
for(const n of ['costLayerStats','consumeFifo','addFifoLayer','adjustFifoLayers','revisePurchaseLayers','restoreSaleItemToStock'])vm.runInNewContext(extract(n),ctx);
test('receipts, receipt corrections and stocktakes retain the master average',()=>{assert.equal(ctx.addFifoLayer(raw,3,20000,{}).averageCost,8000);assert.equal(ctx.addFifoLayer(raw,3,20000,{}).inventoryValue,40000);assert.equal(ctx.adjustFifoLayers(raw,0,20000,{}).averageCost,8000);assert.equal(ctx.adjustFifoLayers(raw,4,20000,{}).inventoryValue,32000);assert.equal(ctx.revisePurchaseLayers(raw,'p',{qty:2},{qty:3},20000,new Date()).averageCost,8000);});
test('returning an old sale restores stock at current master cost without replacing it with historical cost',()=>{const r=ctx.restoreSaleItemToStock(raw,{qty:1,lineCost:14500,fifoBreakdown:[{layerId:'old',qty:1,unitCost:14500}]});assert.equal(r.stock,3);assert.equal(r.raw.averageCost,8000);assert.equal(ctx.costLayerStats(r.raw).inventoryValue,24000);});
test('browser and server execute the same average cost module',()=>{const context={};vm.runInNewContext(fs.readFileSync('functions/inventoryAverageCost.js','utf8'),context);assert.equal(context.YouziInventoryAverageCost.consume(raw,1).costTotal,model.consume(raw,1).costTotal);for(const f of ['portal.html','operations-hub.html']){const html=fs.readFileSync(f,'utf8');assert(html.indexOf('functions/inventoryAverageCost.js')<html.indexOf('<script src="operations-phase1.js'));}});
