const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {database}=require('./helpers/security-fixtures.cjs');const {createProductVideoAccess,videoBrandProfile}=require('../functions/productVideoAccess');const {detailImageMap,thumbnail}=require('../functions/productThumbnail');
function setup(){const f=database({'opsInternalProducts/p1':{internalSku:'P1',internalName:'Piano',currentStock:5,productVideos:[]}}),files=new Map();let creates=0;const bucket={name:'demo',file:path=>({createResumableUpload:async options=>{creates++;assert.equal(options.origin,'https://danny700808.github.io');assert.equal(options.preconditionOpts.ifGenerationMatch,0);files.set(path,{size:'16',contentType:'video/mp4',metadata:{},head:Buffer.from('0000ftypisom0000')});return ['https://storage.googleapis.com/upload/session'];},getMetadata:async()=>[files.get(path)],download:async()=>[files.get(path).head],setMetadata:async data=>Object.assign(files.get(path),data)})};let enabled=true;const api=createProductVideoAccess({...f,bucket,authorize:async token=>{if(!enabled||token!=='pin-session')throw Error('denied');}});return {...f,files,api,creates:()=>creates,disable:()=>enabled=false};}
const input={token:'pin-session',productId:'p1',operator:'Name',sizeBytes:16,contentType:'video/mp4',fileName:'clip.mp4',durationSeconds:80};
test('video original and branding queue are linked to the selected product exactly once',async()=>{const f=setup(),start=await f.api.start(input),args={token:input.token,uploadId:start.uploadId};const [a,b]=await Promise.all([f.api.finish(args),f.api.finish(args)]);assert.equal(a.video.url,b.video.url);const p=f.rows.get('opsInternalProducts/p1');assert.equal(p.productVideos.length,1);assert.equal(p.currentStock,5);assert.equal(p.productVideos[0].createdBy,'Name');assert.equal(p.productVideos[0].videoBrandStatus,'pending');assert.equal(p.productVideos[0].shopeeClipDurationSeconds,54.7);assert.equal(p.productVideos[0].shopeeClipSelectionMode,'auto-best-segment');assert.deepEqual(f.rows.get('opsProductListingCases/p1').mediaQueueKinds,['product-video']);assert.equal(p.productVideos[0].videoBrandProfile.intro.durationSeconds,3);});
test('video uploads require PIN session, supported type, size limit and active product',async()=>{const f=setup();for(const data of [{token:'bad'},{contentType:'text/html'},{sizeBytes:513*1024*1024},{productId:'../other'},{operator:''}])await assert.rejects(f.api.start({...input,...data}));assert.equal(f.creates(),0);f.rows.get('opsInternalProducts/p1').enabled=false;await assert.rejects(f.api.start(input));});
test('incomplete and invalid video content cannot reach the product',async()=>{const f=setup(),start=await f.api.start(input);const file=[...f.files.values()][0];file.size='3';await assert.rejects(f.api.finish({token:input.token,uploadId:start.uploadId}),/完整/);file.size='16';file.head=Buffer.from('not a video file');await assert.rejects(f.api.finish({token:input.token,uploadId:start.uploadId}),/影片格式/);assert.equal(f.rows.get('opsInternalProducts/p1').productVideos.length,0);});
test('expired PIN and three-video limit are rechecked before attachment',async()=>{const f=setup(),start=await f.api.start(input);f.disable();await assert.rejects(f.api.finish({token:input.token,uploadId:start.uploadId}),/denied/);const g=setup(),s=await g.api.start(input);g.rows.get('opsInternalProducts/p1').productVideos=[{},{},{}];await assert.rejects(g.api.finish({token:input.token,uploadId:s.uploadId}),/3 段/);});
test('video finish cannot reuse another PIN session upload',async()=>{const f=setup(),start=await f.api.start(input);f.rows.get('inventoryMediaUploads/'+start.uploadId).sessionHash='different';await assert.rejects(f.api.finish({token:input.token,uploadId:start.uploadId}),/失效/);});
test('exact variant cards never substitute a sibling image and blank cards use group',()=>{const docs=[{id:'root',data:()=>({productId:'root',variantGroupEnabled:true,variantGroupPrimaryImageUrl:'root-specific',variantGroupItems:[{productId:'red',imageUrls:['red-specific']},{productId:'blue',imageUrls:['blue-specific']}],updatedAt:new Date()})}];const map=detailImageMap(docs);assert.equal(thumbnail({variantImageUrls:['old-red'],parentImageUrls:['group']},'red',map).detailThumbnailUrl,'red-specific');assert.equal(thumbnail({parentImageUrls:['group']},'blue',map).detailThumbnailUrl,'blue-specific');assert.deepEqual(thumbnail({parentImageUrls:['group']},'missing',map),{detailThumbnailUrl:'',groupThumbnailUrl:'group'});});
test('mobile video profile matches existing renderer contract',()=>{const source=fs.readFileSync('operations-phase1.js','utf8'),start=source.indexOf('  const PRODUCT_VIDEO_BRAND_PROFILE = '),end=source.indexOf('\n  const PRODUCT_LISTING_INTENTS',start),ctx={};vm.createContext(ctx);vm.runInContext(source.slice(start,end)+';globalThis.profile=PRODUCT_VIDEO_BRAND_PROFILE;',ctx);assert.deepEqual(require('../functions/productVideoBrandProfile.json'),JSON.parse(JSON.stringify(ctx.profile)));assert.match(videoBrandProfile().intro.assetUrl,/^https:\/\/danny700808.github.io\/play-card\/assets\//);});
