const assert=require('node:assert/strict');const {buildNativeEducationDays:build}=require('../functions/nativeEducationDaily');
const payment={id:'tx',date:'2026-09-15',amount:2800,type:'payment',status:'confirmed',active:true,studentId:'s'};
const group={id:'g',date:'2026-09-15',active:true,status:'attended',studentIds:['a','b'],lessonPrice:900,teacherAmount:540,schoolShare:360};
let rows=build({payroll:[group,{...group,id:'cancelled',active:false}],transactions:[payment,{...payment,id:'refund',amount:300,type:'refund'},{...payment,id:'old',date:'2026-09-14'}],periods:[{transactions:[payment]}]});
assert.equal(rows[0].sessions.length,1,'group payroll is counted once');assert.equal(rows[0].summary.tuitionReceived,2500,'cash deducts refunds and deduplicates embedded transactions');assert.equal(rows[0].summary.schoolShare,360);assert.equal(rows.length,1,'cutover excludes old daily imports');
rows=build({bookings:[{id:'b',date:'2026-09-15',active:true,status:'confirmed',paymentStatus:'onsite_unpaid',amount:200}],changes:[{id:'change',active:true,event:{id:'rental-b',portalBookingId:'b',date:'2026-09-15',type:'rental',rentalPaymentStatus:'paid',rentalFee:200}}]});assert.equal(rows[0].summary.roomRentalReceived,0,'authoritative unpaid booking replaces its schedule copy');
rows=build({mirrorRentals:[{source:{id:'m',type:'rental',date:'2026-09-15',rentalFee:100,rentalPaymentStatus:'paid'}}],changes:[{active:true,action:'cancel',sourceDate:'2026-09-15',sourceEventId:'m',event:{id:'c',type:'rental',date:'2026-09-15',status:'cancelled'}}],existingDates:['2026-09-15']});assert.equal(rows[0].summary.roomRentalReceived,0,'cancellation clears previously projected revenue');
rows=build({changes:[{id:'new',active:true,action:'extra_lesson',event:{id:'r',date:'2026-09-16',type:'rental',rentalFee:100,rentalPaymentStatus:'paid'}}],settings:[{date:'2026-09-16',eventIds:['r'],fields:{rentalFee:150}}]});assert.equal(rows[0].summary.roomRentalReceived,150,'manager edits flow into daily totals');
rows=build({transactions:[payment,{...payment,active:false}],existingDates:['2026-09-15']});assert.equal(rows[0].summary.tuitionReceived,0,'inactive transaction does not remain as cash');console.log('Native education daily cases passed');
