const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('operations-phase1.js','utf8');
function code(name){const start=source.search(new RegExp('(?:async )?function '+name+'\\('));assert.ok(start>=0,name);const rest=source.slice(start+3),end=rest.search(/\n  (?:async )?function /);return source.slice(start,start+3+end);}
function harness({retry=false,fail=false}={}){
 const names=['products','sales','inventory','customers','points','receivables','receivablePayments','platformInventoryQueue'];const COLLECTIONS=Object.fromEntries(names.map(n=>[n,n]));let seq=0,commits=0,reads=0,renders=0;
 const dbRows=new Map([['products/p1',{currentStock:10,averageCost:30,internalName:'琴弦',internalSku:'101'}],['products/p2',{currentStock:5,averageCost:20,internalName:'琴袋',internalSku:'102'}],['customers/c1',{name:'測試會員',customerType:'member',pointBalance:100}]]);
 function ref(collection,id='new'+(++seq)){return {id,path:collection+'/'+id,parent:{id:collection}};}
 const state={cart:[{productId:'p1',qty:2,unitPrice:100,sku:'101',name:'琴弦'},{productId:'p2',qty:1,unitPrice:50,sku:'102',name:'琴袋'}],internalProducts:[],sales:[],inventory:[],customers:[],pointTransactions:[],receivables:[],receivablePayments:[]};
 state.db={collection:name=>({doc:id=>ref(name,id)}),runTransaction:async callback=>{
  async function attempt(){const pending=[];const tx={get:async r=>{reads++;return {exists:dbRows.has(r.path),data:()=>({...dbRows.get(r.path)})};},set:(r,d)=>pending.push([r,d]),update:(r,d)=>pending.push([r,{...dbRows.get(r.path),...d}])};const result=await callback(tx);return {pending,result};}
  if(retry)await attempt();const a=await attempt();if(fail)throw new Error('offline');a.pending.forEach(([r,d])=>dbRows.set(r.path,d));commits++;return a.result;
 }};
 const normalize=raw=>({...raw,id:raw.__id});
 const ctx={state,COLLECTIONS,Map,Array,Date,Number,Math,FormData:class{constructor(form){this.form=form;}get(k){return this.form[k]??null;}},clean:v=>String(v??'').trim(),numberOrNull:v=>v==null||v===''?null:Number(v),uid:()=>String(++seq),sum:(a,f)=>a.reduce((n,r)=>n+f(r),0),consumeFifo:(raw,qty)=>({costTotal:raw.averageCost*qty,unknownCostQty:0,layers:[],inventoryValue:(raw.currentStock-qty)*raw.averageCost,averageCost:raw.averageCost,costIncomplete:false,breakdown:[]}),estimatePreorderCost:(raw,qty)=>({costTotal:raw.averageCost*qty,unknownCostQty:0,breakdown:[]}),normalizeCustomer:normalize,maxRedeemablePoints:c=>c?.pointBalance||0,membershipRuleForDate:()=>({redeemPoints:1,year:2026,rewardPercent:1}),pointDiscount:n=>n,calculatePreparedRewardPoints:()=>5,productRewardPercent:()=>1,serverTimestamp:()=>({serverTime:true}),userLabel:()=>'測試',VERSION:'test',writeAudit:()=>Promise.resolve(),toast:()=>{},closeDrawer:()=>{},render:()=>renders++,saveFastStateCache:()=>{},mergeCatalog:()=>{},normalizeInternal:raw=>({...raw,docId:raw.__id}),normalizeSale:normalize,normalizeInventory:normalize,normalizePointTransaction:normalize,normalizeReceivable:normalize,normalizeReceivablePayment:normalize};
 vm.createContext(ctx);vm.runInContext(['queueInventorySyncInTransaction','trackCheckoutTransaction','applyCheckoutChanges','saveCheckoutV4'].map(code).join('\n'),ctx);
 return {ctx,state,dbRows,stats:()=>({commits,reads,renders}),submit:form=>ctx.saveCheckoutV4({paymentStatus:'paid',paymentMethod:'現金',...form})};
}
test('cash checkout only reads purchased products, mirrors committed stock and sale, and clears cart',async()=>{
 const h=harness();await h.submit({});assert.equal(h.dbRows.get('products/p1').currentStock,8);assert.equal(h.dbRows.get('products/p2').currentStock,4);assert.equal(h.state.sales[0].total,250);assert.equal(h.state.sales[0].costTotal,80);assert.equal(h.state.inventory.length,2);assert.equal(h.state.cart.length,0);assert.deepEqual(h.stats(),{commits:1,reads:2,renders:1});assert.equal(h.state.internalProducts.find(p=>p.docId==='p1').currentStock,8);
});
test('transaction retry only applies the successful attempt once, including member point balance',async()=>{
 const h=harness({retry:true});await h.submit({customerId:'c1',pointsToRedeem:10,earnPointsEnabled:'true'});assert.equal(h.state.sales.length,1);assert.equal(h.state.inventory.length,2);assert.equal(h.state.sales[0].total,240);assert.equal(h.state.pointTransactions.length,2);assert.equal(h.state.customers[0].pointBalance,95);assert.equal(h.stats().commits,1);
});
test('preorder deposit updates receivable and payment without reducing stock',async()=>{
 const h=harness();await h.submit({orderType:'preorder',customerId:'c1',receivedAmount:50});assert.equal(h.dbRows.get('products/p1').currentStock,10);assert.equal(h.state.inventory.length,0);assert.equal(h.state.receivables[0].outstandingAmount,200);assert.equal(h.state.receivablePayments[0].amount,50);assert.equal(h.state.sales[0].total,250);assert.equal(h.state.sales[0].fulfillmentStatus,'waiting_stock');
});
test('failed transaction keeps cart and never updates local sales or inventory',async()=>{
 const h=harness({fail:true});await assert.rejects(h.submit({}),/offline/);assert.equal(h.state.cart.length,2);assert.equal(h.state.sales.length,0);assert.equal(h.dbRows.get('products/p1').currentStock,10);assert.equal(h.stats().renders,0);
});
test('search caps DOM cards, more remains reachable and a new query resets the page',()=>{
 const rows=Array.from({length:100},(_,i)=>({docId:String(i),sku:String(i),initialized:true,name:'測試',variantImageUrls:['https://test/variant.jpg'],imageUrl:'https://test/main.jpg'}));const ctx={state:{posSearch:'測'},POS_PAGE_SIZE:24,lower:v=>String(v).toLowerCase(),catalogRowsInSkuOrder:()=>rows,catalogMatchesSearch:()=>true,safeUrl:v=>v||'',attr:v=>v,escapeHtml:v=>v,formatNumber:v=>v,money:v=>v};vm.createContext(ctx);vm.runInContext(code('productDisplayImage')+code('posSearchResultsHtml'),ctx);let html=ctx.posSearchResultsHtml();assert.equal((html.match(/data-action="cart-add"/g)||[]).length,24);assert.match(html,/pos-load-more/);assert.match(html,/variant.jpg/);ctx.state.posVisible=48;assert.equal((ctx.posSearchResultsHtml().match(/data-action="cart-add"/g)||[]).length,48);ctx.state.posSearch='另一個';assert.equal((ctx.posSearchResultsHtml().match(/data-action="cart-add"/g)||[]).length,24);
});
test('barcode and sales use the variant photo before parent and main photos',()=>{
 const barcode=fs.readFileSync('barcode-print.js','utf8');const start=barcode.indexOf('  function imageList('),end=barcode.indexOf('  function normalize(',start);const ctx={safeUrl:v=>/^https?:/.test(v||'')?v:''};vm.createContext(ctx);vm.runInContext(barcode.slice(start,end)+code('productDisplayImage'),ctx);for(const p of [{variantImageUrls:['https://test/variant'],parentImageUrls:['https://test/parent'],imageUrl:'https://test/main'},{parentImageUrls:['https://test/parent'],imageUrl:'https://test/main'},{imageUrls:['https://test/general'],imageUrl:'https://test/main'}])assert.equal(ctx.imageList(p)[0],ctx.productDisplayImage(p));
});
test('media status only fetches visible cards, caps concurrency at two and reuses cached receipts',async()=>{
 let observer,active=0,maxActive=0,requests=0;const finish=[];const cards=Array.from({length:24},(_,i)=>({dataset:{id:String(i)},isConnected:true}));const products=new Map(cards.map(c=>[c.dataset.id,{docId:c.dataset.id}]));const ctx={state:{view:'products',db:{}},Map,Date,Array,global:{IntersectionObserver:class{constructor(cb){this.cb=cb;observer=this;}observe(){}unobserve(){}disconnect(){}}},queryAll:()=>cards,catalogById:id=>products.get(id),refreshProductInlineMedia:()=>{},normalizeProductVideoRecords:v=>v,loadProductMediaReceipt:async p=>{requests++;active++;maxActive=Math.max(maxActive,active);await new Promise(r=>finish.push(r));active--;vm.runInContext(`productMediaCache.set('${p.docId}',{at:Date.now(),raw:{}})`,ctx);}};
 vm.createContext(ctx);const start=source.indexOf('  let productMediaObserver='),end=source.indexOf('  function productCreatedTime',start);vm.runInContext(source.slice(start,end),ctx);ctx.loadVisibleProductMediaPresence();assert.equal(requests,0);observer.cb(cards.slice(0,3).map(target=>({target,isIntersecting:true})));assert.equal(requests,2);finish.shift()();await new Promise(r=>setImmediate(r));assert.equal(requests,3);while(finish.length)finish.shift()();await new Promise(r=>setImmediate(r));assert.equal(maxActive,2);ctx.loadVisibleProductMediaPresence();observer.cb(cards.slice(0,3).map(target=>({target,isIntersecting:true})));assert.equal(requests,3);
});
