const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const data=fs.readFileSync('course-scheduler-data.js','utf8');
function normalize(row){const c=vm.createContext({array:v=>Array.isArray(v)?v:[],clean:v=>String(v??'').trim(),clone:v=>JSON.parse(JSON.stringify(v)),safeId:(p,id)=>id,numberOf:v=>Number(v)||0,dateKey:v=>String(v||'').slice(0,10)});vm.runInContext(data.slice(data.indexOf('  function normalizeTeacherPayroll('),data.indexOf('  function normalizeTeacherAdjustments(')),c);return c.normalizeTeacherPayroll({teacherPayroll:[{id:'pay',teacherId:'t',date:'2026-09-20',...row}]})[0];}
for(const file of ['course-scheduler.js','operations-course-inline-runtime.js']){
 const source=fs.readFileSync(file,'utf8');
 function label(row,periods=[]){const c=vm.createContext({clean:v=>String(v??'').trim(),state:{tuitionPeriods:periods}});vm.runInContext(source.slice(source.indexOf('  function payrollPlanText('),source.indexOf('  function splitText(')),c);return c.payrollPlanText(normalize(row));}
 test(file+' preserves historical plan instead of instrument or current plan',()=>{assert.equal(label({subjectName:'木吉他',planSnapshot:{name:'外聘（6/4）2800'},planName:'外聘（7/3）3200'}),'外聘（6/4）2800');assert.equal(label({subjectName:'木吉他',chargeName:'外聘（7/3）3200'}),'外聘（7/3）3200');assert.match(source,/<th>授課／收費方案<\/th>/);assert.match(source,/esc\(payrollPlanText\(row\)\)/);});
 test(file+' resolves only the recorded period and handles missing/special/group plans',()=>{const periods=[{id:'p',studentId:'s',planSnapshot:{name:'外聘（6/4）2800'}}];assert.equal(label({periodId:'p',studentId:'s'},periods),'外聘（6/4）2800');assert.equal(label({periodId:'p',studentId:'other'},periods),'未記錄方案');assert.equal(label({subjectName:'木吉他'},periods),'未記錄方案');assert.equal(label({specialLesson:true}),'贈送／特殊加課');assert.equal(label({payrollCalculation:{students:[{inputs:{planSnapshot:{name:'方案甲'}}},{inputs:{planSnapshot:{name:'方案乙'}}}]}}),'方案甲、方案乙');});
}
