'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(require.resolve('../private-calendar.js'),'utf8');
const mapping=source.slice(source.indexOf(' function workEvent('),source.indexOf(' function message('));
const refresh=source.slice(source.indexOf(' async function refresh(){'),source.indexOf(' const dayKey='));
function setup(tasks,error){const notices=[],ctx={S:{},calendarSession:'owner-session',message:(...v)=>notices.push(v),range:()=>({start:'2026-09-01',end:'2026-10-01'}),api:async action=>action==='status'?{googleConnected:false}:{events:[{id:'private-1',title:'private'}]},workApi:async()=>{if(error)throw error;return {tasks};},render(){},settingsRender(){},$:()=>({})};vm.createContext(ctx);vm.runInContext(mapping+refresh,ctx);return {ctx,notices};}
test('private calendar displays all published team work with stable separate IDs; refresh never duplicates',async()=>{const {ctx}=setup([{id:'private-1',assignedTo:'owner',createdName:'Teacher',status:'pending'},{id:'draft',assignedTo:'owner',draft:true},{id:'other',assignedTo:'member'}]);await ctx.refresh();assert.equal(ctx.S.events.length,3);assert.equal(ctx.S.events[1].id,'shared:private-1');assert.equal(ctx.S.events[1].taskId,'private-1');assert.equal(ctx.S.events[1].createdName,'Teacher');await ctx.refresh();assert.equal(ctx.S.events.length,3);});
test('shared service failure is visible while private events remain available; authentication failure propagates',async()=>{const a=setup([],Error('unavailable'));await a.ctx.refresh();assert.equal(a.ctx.S.events.length,1);assert.match(a.notices.at(-1)[0],/unavailable/);const e=Object.assign(Error('expired'),{code:'functions/unauthenticated'}),b=setup([],e);await assert.rejects(b.ctx.refresh(),/expired/);});
test('notification detail opens inside private calendar before legacy shared redirect',async()=>{const code=source.slice(source.indexOf(' async function openCalendar('),source.indexOf(' async function loginTask('));let shown='',redirect='';const els={};const ctx={calendarSession:'',sessionStorage:{setItem(){}},access:async()=>({autoFace:true}),refresh:async()=>{},syncSharedDate(){},$:id=>els[id]||(els[id]={}),URLSearchParams,location:{search:'?shared=1&task=job-123',replace:url=>redirect=url},showWork:async(id,focus)=>{assert.equal(focus,true);shown=id;}};vm.createContext(ctx);vm.runInContext(code,ctx);await ctx.openCalendar({token:'owner-session'});assert.equal(shown,'job-123');assert.equal(redirect,'');});
test('work details stay in a modal, escape member content and expose scoped attachment buttons',async()=>{const nodes={};const $=id=>nodes[id]||(nodes[id]={open:false,showModal(){this.open=true;},addEventListener(){},replaceChildren(){this.innerHTML='';}});const task={id:'job',title:'<unsafe>',createdName:'Teacher <A>',assignedTo:'owner',status:'pending',note:'notes',start:'2026-09-27T01:00:00Z',end:'2026-09-27T02:00:00Z',assets:[{id:'asset',name:'photo.png',mime:'image/png'}]};const ctx={$,calendarSession:'valid',S:{events:[]},workApi:async()=>({task}),esc:s=>String(s).replaceAll('<','&lt;').replaceAll('>','&gt;'),eventTime:()=> '9/27 09:00',render(){},refresh:async()=>{},dayKey:()=> '2026-09-27',showAttachment(){},safely(){}};vm.createContext(ctx);const detail=source.slice(source.indexOf(' let workPreviewVersion='),source.indexOf(' function renderDay('));vm.runInContext(mapping+detail,ctx);await ctx.showWork('job');assert.equal(nodes.workViewer.open,true);assert.match(nodes.workBody.innerHTML,/Teacher &lt;A&gt;/);assert.match(nodes.workBody.innerHTML,/data-work-asset="asset"/);assert.equal(ctx.S.events[0].source,'shared');assert.equal(nodes.workProgressControls.hidden,false);});
