'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(require.resolve('../private-calendar.js'),'utf8');
function harness(configured=true){const elements={},calls=[],S={status:{googleConfigured:configured,googleConnected:true},googleConnectionError:'Google 授權已失效，請重新連接。'};const ctx={S,$:id=>elements[id]||(elements[id]={disabled:false,showModal(){this.open=true;}}),settingsRender(){calls.push('render');},api:async action=>{calls.push(action);return {url:'https://accounts.google.com/example'};},location:{assign:url=>calls.push(url)}};vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf(' function connectionRender(){'),source.indexOf(' async function refresh(){')),ctx);return {ctx,elements,calls,S};}
test('expired Google connection exposes an actionable recovery control',()=>{const {ctx,elements,S}=harness();ctx.connectionRender();assert.equal(elements.connection.hidden,false);assert.match(elements.connectionMessage.textContent,/不完整/);S.googleConnectionError='';ctx.connectionRender();assert.equal(elements.connection.hidden,true);});
test('reconnect obtains an owner-authorized URL and navigates to Google',async()=>{const {ctx,calls,elements}=harness();await ctx.connectGoogle();assert.deepEqual(calls,['connect','https://accounts.google.com/example']);assert.equal(elements.reconnectGoogle.disabled,false);});
test('failed reconnect is visible on homepage and remains retryable',async()=>{const {ctx,elements}=harness();ctx.api=async()=>{throw Error('連線失敗');};await ctx.connectGoogle();assert.equal(elements.connectionStatus.textContent,'連線失敗');assert.equal(elements.reconnectGoogle.disabled,false);});
test('missing OAuth configuration opens settings instead of dead-end connect',async()=>{const {ctx,elements,calls}=harness(false);await ctx.connectGoogle();assert.deepEqual(calls,['render']);assert.equal(elements.settings.open,true);assert.equal(elements.settings.scrollTop,0);});
test('duplicate reconnect taps do not create multiple authorization requests',async()=>{const {ctx,calls}=harness();await Promise.all([ctx.connectGoogle(),ctx.connectGoogle()]);assert.equal(calls.filter(c=>c==='connect').length,1);});
