const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../operations-phase1.js'),'utf8');
const context={productEditorImages:()=>['sample.jpg'],clean:x=>String(x||''),attr:x=>String(x||'').replaceAll('"','&quot;'),escapeHtml:x=>String(x||'').replaceAll('<','&lt;'),URL,normalizeProductVideoRecords:x=>x||[],physicalProductImageTrayHtml:()=>'<div>photo-tray</div>',productPlatformStatusHtml:()=>'<div>listing-status</div>',PRODUCT_LISTING_PLATFORMS:[{key:'momo',label:'MOMO'},{key:'shopee',label:'蝦皮'}]};
vm.createContext(context);vm.runInContext(source.slice(source.indexOf('  function productYoutubeId('),source.indexOf('  function refreshProductInlineMedia(')),context);
test('YouTube player uses validated ID, supports fullscreen and keeps originals untouched',()=>{
 const p={docId:'one',productVideos:[{url:'original.mp4',youtubeVideoId:'tO2AXQxknes',platformVideoResults:{shopee:{status:'completed'}}}],mediaReceipt:{physicalImagePlatformResults:{momo:{status:'waiting-listing'}}},physicalImageUrls:['photo']};
 const html=context.productInlineMediaHtml(p);assert.ok(html.includes('youtube.com/embed/tO2AXQxknes'));assert.ok(html.includes('allowfullscreen'));assert.ok(!html.includes('<video'));assert.equal(p.productVideos[0].url,'original.mp4');assert.ok(!html.includes('① 商品上架'));assert.ok(!html.includes('② 補實體圖與影片'));assert.ok(!html.includes('媒體通路進度'));assert.ok(html.includes('細項圖片'));
 assert.ok(html.indexOf('photo-tray')<html.indexOf('youtube.com/embed'));
});
test('unpublished clip remains local preview; invalid video ID cannot inject frame',()=>{const html=context.productInlineMediaHtml({docId:'two',productVideos:[{url:'test.mp4',youtubeVideoId:'" onload="bad'}]});assert.ok(html.includes('<video'));assert.ok(!html.includes('<iframe'));});
test('media presence never treats a new source as uploaded via an old receipt',()=>{vm.runInContext(source.slice(source.indexOf('  function productMediaPresenceBadges('),source.indexOf('  function productCreatedTime(')),context);const html=context.productMediaPresenceBadges({docId:'three',physicalImageUrls:['old','new'],mediaReceipt:{physicalImagePlatformResults:{momo:{status:'completed',sourceImageUrls:['old']}}}});assert.ok(!html.includes('is-present'));assert.ok(html.includes('尚未完成通路上傳'));});
test('current frontend brand contract rejects old geometry',()=>{assert.ok(source.includes('heightRatio:0.20'));assert.ok(source.includes('overlapHeaderAndContent:false'));assert.ok(source.includes("widthPx:700,heightPx:1000,aspectRatio:'7:10'"));assert.ok(!source.includes('heightRatio:1/9'));});
test('media upload handlers prefer the visible product over stale media-page selection',()=>{assert.equal((source.match(/event\.target\.closest\('\[data-product-id\]'\)/g)||[]).length,2);});
