const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync('functions/coursePortal.js','utf8');
const extract=(a,b)=>source.slice(source.indexOf(a),source.indexOf(b));
function fixture(stop={teacherId:'t',studentId:'s',subjectId:'p',effectiveDate:'2026-09-01',status:'active'}){const writes=[];const course={id:'c',teacherId:'t',subjectId:'p',studentIds:['s','other'],startTime:'13:00',endTime:'14:00'};const ref=(collection,id)=>({collection,id,get:async()=>({id,exists:collection==='coursePortalStudentSuspensions',data:()=>stop})});const c={clean:v=>String(v||''),dateKey:v=>v,sourceId:r=>r.id,eventTeacherId:r=>r.teacherId,eventSubjectId:r=>r.subjectId,eventStudentIds:r=>r.studentIds,resourceEvent:r=>({...r}),mirrorRows:async type=>type==='fixedCourses'?[course]:[],db:{collection:name=>({doc:id=>ref(name,id)}),runTransaction:async fn=>fn({get:async r=>({exists:r.id==='version',data:()=>({version:1})}),set:(r,data)=>writes.push({r,data}),update:(r,data)=>writes.push({r,data})})},HttpsError:class extends Error{constructor(code,message){super(message);this.code=code;}},jsonValue:v=>v,requireSession:async()=>({teacherId:'t'}),readScheduleVersion:async()=>1,scheduleBundle:async()=>({resourceEvents:[]}),isRoomRentalEvent:()=>false,hash:v=>v,FieldValue:{serverTimestamp:()=>1},scheduleVersionRef:()=>({id:'version'}),assertScheduleWritable:()=>{},currentTaipeiDay:()=> '2026-09-15'};vm.createContext(c);vm.runInContext(extract('async function stoppedRestoreMode(','async function historyStudentEvents('),c);return {c,writes};}
test('stopped course is scoped to its teacher, subject and exact student',async()=>{const {c}=fixture();const mode=await c.stoppedRestoreMode({suspensionId:'stop'},{teacherId:'t'});assert.equal(mode.subjectId,'p');assert.deepEqual(Array.from(mode.source.studentIds),['s']);assert.equal(mode.source.fixedCourseId,'stopped-stop');assert.equal(mode.blockedSourceCourseId,'c');await assert.rejects(c.stoppedRestoreMode({suspensionId:'stop'},{teacherId:'other'}),/不屬於您/);});
test('obsolete stops and path identifiers cannot be reused',async()=>{await assert.rejects(fixture({status:'reactivated',teacherId:'t'}).c.stoppedRestoreMode({suspensionId:'stop'},{teacherId:'t'}));await assert.rejects(fixture().c.stoppedRestoreMode({suspensionId:'a/b'},{teacherId:'t'}));});
test('opening stopped fixed options does not change any data',async()=>{const {c,writes}=fixture();const mode=await c.irregularRestoreMode({suspensionId:'stop',action:'permanent_move'},{teacherId:'t'});assert.equal(c.irregularSource(mode,'2026-09-16').date,'2026-09-16');assert.equal(writes.length,0);});
test('moving a stopped student to irregular preserves the stopped interval and excludes group siblings',async()=>{const {c,writes}=fixture();await c.teacherSetIrregular({suspensionId:'stop',sourceDate:'2026-09-15'});const mode=writes.find(w=>w.r.collection==='coursePortalIrregularCourses').data;assert.equal(mode.effectiveDate,'2026-09-01');assert.equal(mode.enabled,true);assert.equal(mode.resumedFrom,'');assert.deepEqual(Array.from(mode.studentIds),['s']);assert.equal(writes.find(w=>w.r.collection==='coursePortalStudentSuspensions').data.status,'reactivated');});
test('weekly and fortnightly selection retains fallback and rejects other intervals',()=>{const part=extract("  if (action === 'permanent_move' && data.frequencyWeeks",'  let recurrenceEndDate');for(const [selected,expected] of [[1,1],[2,2],[undefined,2]]){const c={action:'permanent_move',data:{frequencyWeeks:selected},sourceSeries:{frequencyWeeks:2},safeFrequencyWeeks:v=>v===2?2:1,HttpsError:Error};vm.createContext(c);vm.runInContext(part+';this.answer=frequencyWeeks;',c);assert.equal(c.answer,expected);}const c={action:'permanent_move',data:{frequencyWeeks:3},HttpsError:Error};vm.createContext(c);assert.throws(()=>vm.runInContext(part,c));});
test('irregular roster keeps active group members and separates only the stopped student',()=>{const line=source.split('\n').find(l=>l.trim().startsWith('irregularCourses: bundle.irregularModes.filter'));const expression=line.trim().slice('irregularCourses: '.length).replace(/,$/,'');const c={clean:v=>String(v||''),currentTaipeiDay:()=> '2026-09-15',session:{teacherId:'t'},bundle:{maps:{students:{s:{name:'Stopped'},other:{name:'Active'}}},irregularModes:[{id:'i',teacherId:'t',subjectId:'p',studentIds:['s','other'],source:{studentIds:['s','other']}},{id:'foreign',teacherId:'other',subjectId:'p',studentIds:['other']}],suspensions:[{status:'active',teacherId:'t',studentId:'s',subjectId:'p'}]}};vm.createContext(c);vm.runInContext('this.result='+expression,c);assert.equal(c.result.length,1);assert.deepEqual(Array.from(c.result[0].studentIds),['other']);assert.deepEqual(Array.from(c.result[0].source.studentIds),['other']);});

test('a returning group member does not revive their old group slot or hide classmates',()=>{const c={eventStudentIds:r=>r.studentIds,courseSourceIds:r=>[r.fixedCourseId],normalizeScheduleStatus:v=>v,clean:v=>String(v||''),eventTeacherId:r=>r.teacherId,eventSubjectId:r=>r.subjectId,eventDate:r=>r.date};vm.createContext(c);vm.runInContext(extract('function irregularPlaceholder(','async function stoppedRestoreMode('),c);const group={teacherId:'t',subjectId:'p',fixedCourseId:'old-group',studentIds:['s','other'],date:'2026-09-29',type:'fixed',status:'scheduled'};const mode={teacherId:'t',subjectId:'p',studentIds:['s'],effectiveDate:'2026-09-01',resumedFrom:'2026-09-15',blockedSourceCourseId:'old-group'};assert.deepEqual(Array.from(c.applyIrregularStudentModes(group,[mode]).studentIds),['other']);const own={...group,fixedCourseId:'stopped-stop',studentIds:['s']};assert.deepEqual(Array.from(c.applyIrregularStudentModes(own,[mode]).studentIds),['s']);assert.equal(c.applyIrregularStudentModes({...own,date:'2026-09-08'},[mode]),null);assert.deepEqual(Array.from(c.applyIrregularStudentModes({...group,status:'attended'},[mode]).studentIds),['s','other']);});
