const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{test}=require('node:test');
const s=fs.readFileSync('functions/coursePortal.js','utf8');const fn=s.slice(s.indexOf('async function dailyTeacherCourseReminders('),s.indexOf('async function dailyStudentReminders('));
function fixture(events=[],prefs={}){
 const sent=new Map(),reads=[];const c={...require('../functions/portalNotificationPolicy'),TAIPEI:'Asia/Taipei',Intl,Date,console,clean:v=>String(v||''),weekday:d=>new Date(d+'T00:00:00Z').getUTCDay(),addDays:(d,n)=>new Date(Date.parse(d+'T00:00:00Z')+n*86400000).toISOString().slice(0,10),scheduleBundle:async(a,b)=>{reads.push([a,b]);return {resourceEvents:events,maps:{}}},eventTeacherId:r=>r.teacherId||'t',normalizeScheduleStatus:v=>v,eventDate:r=>r.date,eventStart:r=>r.start||'12:00',teacherReminderLessonLine:r=>r.date+' '+(r.name||'課程明細'),hash:v=>v,PORTAL_BASE:'https://example.test',queueCoursePortalNotice:async(id,row)=>{if(!sent.has(id))sent.set(id,row)},db:{collection:name=>name==='coursePortalTeacherReminderSettings'?{get:async()=>({docs:[{id:'t',data:()=>prefs}]})}:{where:()=>({get:async()=>({docs:[1,2].map(id=>({id,data:()=>({teacherId:'t',lineUserId:'line'})}))})})}}};
 vm.runInNewContext(fn,c);return {sent,reads,run:(at)=>c.dailyTeacherCourseReminders(null,null,new Date(at))};
}
const row=(date,status='scheduled',name='課程明細')=>({date,status,name});
test('morning includes today and only yesterday; Tuesday uses Sunday',async()=>{
 const f=fixture([row('2026-09-13'),row('2026-09-14','scheduled','不應出現星期一'),row('2026-09-12','scheduled','不應出現更早'),row('2026-09-15')]);await f.run('2026-09-15T01:00:00Z');const body=[...f.sent.values()][0].body;assert.match(body,/星期日/);assert.match(body,/今日課程/);assert.doesNotMatch(body,/不應出現/);assert.match(body,/下次請記得當天要點選請假/);assert.deepEqual(f.reads,[['2026-09-13','2026-09-15']]);
});
test('no Monday or wrong-hour sends or data reads',async()=>{const f=fixture();for(const at of ['2026-09-14T01:00:00Z','2026-09-14T14:00:00Z','2026-09-15T02:00:00Z'])await f.run(at);assert.equal(f.reads.length,0)});
test('today opt-out retains yesterday and never chases older records',async()=>{const f=fixture([row('2026-09-15'),row('2026-09-16'),row('2026-09-14','scheduled','古老')],{todayCourses:false});await f.run('2026-09-16T01:00:00Z');const body=[...f.sent.values()][0].body;assert.doesNotMatch(body,/今日課程|古老|2026-09-16/);assert.match(body,/2026-09-15/)});
test('evening only unfinished today, excludes attended leave cancelled conflict and other teachers',async()=>{const f=fixture([row('2026-09-15'),row('2026-09-14','scheduled','古老'),...['attended','leave','cancelled','pending_conflict'].map(x=>row('2026-09-15',x,'排除'+x)),{...row('2026-09-15','scheduled','別人'),teacherId:'other'}]);await f.run('2026-09-15T14:00:00Z');const body=[...f.sent.values()][0].body;assert.match(body,/在今天點選請假/);assert.doesNotMatch(body,/古老|排除|別人|今日課程/);assert.deepEqual(f.reads,[['2026-09-15','2026-09-15']]);});
test('evening opt-out and empty reminders are silent',async()=>{const f=fixture([row('2026-09-15')],{eveningAttendance:false});await f.run('2026-09-15T14:00:00Z');assert.equal(f.sent.size,0);const e=fixture();await e.run('2026-09-15T01:00:00Z');await e.run('2026-09-15T14:00:00Z');assert.equal(e.sent.size,0)});
test('duplicate bindings and scheduler retries produce one message per slot, same old morning key',async()=>{const f=fixture([row('2026-09-15')]);for(let i=0;i<2;i++){await f.run('2026-09-15T01:00:00Z');await f.run('2026-09-15T14:00:00Z')}assert.equal(f.sent.size,2);assert([...f.sent.keys()].some(k=>k.startsWith('teacher-daily-2026-09-15|t|')));});
