const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../functions/coursePortal.js'),'utf8');
function context(mirrors,portals=[],existing={}){const writes=[];const doc=(id,data)=>({id,exists:data!==undefined,data:()=>data});const db={collection:collection=>({doc:id=>({collection,id}),where:()=>({collection,query:true})}),runTransaction:async cb=>cb({get:async ref=>ref.collection==='version'?doc('version',{version:1}):ref.query?{docs:(ref.collection==='mirror'?mirrors:portals).map((r,i)=>doc(r.id||String(i),r))}:doc(ref.id,existing[ref.id]),set:(...x)=>writes.push(x),create:(...x)=>writes.push(x)})};class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
const c={db,HttpsError,Set,Map,clean:x=>String(x||'').trim(),sourceId:r=>r.id||r.__id||'',jsonValue:x=>x,mirrorRows:async()=>[{id:'s'}],cents:x=>Number(x)*100,dateKey:x=>x||'',validateTransaction:()=>{},scheduleVersionRef:()=>({collection:'version'}),assertScheduleWritable:()=>{},timeOperationStage:(_,fn)=>fn(),FieldValue:{serverTimestamp:()=>0},TUITION_PERIODS:'portal',TUITION_TRANSACTIONS:'payments',MIRROR:{tuitionPeriods:'mirror'},tuitionBasePaidAmount:()=>0,transactionAmount:()=>0};vm.createContext(c);const mergeStart=source.indexOf('function mergePortalTuitionRows('),mergeEnd=source.indexOf('\nfunction ',mergeStart+1);vm.runInContext(source.slice(mergeStart,mergeEnd),c);const a=source.indexOf('async function adminSaveTuitionPeriods('),b=source.indexOf('\nasync function adminRecordTuitionTransaction(',a);vm.runInContext(source.slice(a,b),c);return{c,writes};}
const row=n=>({id:'new_'+n,studentId:'s',periodNo:n,startDate:'2026-10-01',lessonCount:4,expectedAmount:3000,discount:0,planSnapshot:{splitType:'ratio',splitValue:60},transactions:[]});const mirror=(n,active)=>({sourceActive:active,source:{id:'old_'+n,studentId:'s',periodNo:n,status:'active'}});
(async()=>{let {c,writes}=context([mirror(23,true),mirror(24,false),mirror(25,false)]);let result=await c.adminSaveTuitionPeriods({operationId:'op',periods:[row(24),row(25)]});assert.equal(result.ok,true);assert.equal(result.periods.length,2);assert.equal(writes.filter(([r])=>r.collection==='portal').length,2);
({c}=context([mirror(24,true)]));await assert.rejects(c.adminSaveTuitionPeriods({operationId:'op',periods:[row(24)]}),e=>e.code==='aborted');
({c}=context([mirror(23,true)],[{id:'live24',studentId:'s',periodNo:24,active:true}]));await assert.rejects(c.adminSaveTuitionPeriods({operationId:'op',periods:[row(24)]}),e=>e.code==='aborted');
({c}=context([mirror(24,true)],[{id:'old_24',studentId:'s',periodNo:24,active:false,status:'cancelled'}]));assert.equal((await c.adminSaveTuitionPeriods({operationId:'op',periods:[row(24)]})).ok,true);
({c,writes}=context([],[],{new_24:{...row(24),creationOperationId:'op'}}));result=await c.adminSaveTuitionPeriods({operationId:'op',periods:[row(24)]});assert.equal(result.periods[0].duplicate,true);assert.equal(writes.filter(([r])=>r.collection==='portal').length,0);
const line=source.split('\n').find(x=>x.includes('const peers = mergePortalTuitionRows(mirrorPeers.docs'));assert.ok(line);c.mirrorPeers={docs:[mirror(23,true),mirror(24,false),mirror(25,false)].map(data=>({data:()=>data}))};c.portalPeers={docs:[{id:'cancelled',data:()=>({id:'cancelled',studentId:'s',periodNo:30,active:false})}]};vm.runInContext(line+'\nglobalThis.enrollmentNext=peers.reduce((max,p)=>Math.max(max,Number(p.periodNo)||0),0)+1;',c);assert.equal(c.enrollmentNext,24);
console.log('PASS: inactive 24/25, active collisions, cancelled overlay, duplicate retry, enrollment next=24');})();
